import { Suspense } from "react";
import { notFound } from "next/navigation";
import { getSupabaseAdmin } from "@/lib/supabase";
import { QuestionReviewClient } from "@/components/question-review-client";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { Breadcrumb, BreadcrumbItem, BreadcrumbLink, BreadcrumbList, BreadcrumbPage, BreadcrumbSeparator } from "@/components/ui/breadcrumb";
import { FileText, Calendar, Award } from "lucide-react";

async function getQuestionPaperData(id: string) {
  const supabase = getSupabaseAdmin();

  // Fetch question paper with syllabus info
  const { data: questionPaper, error: paperError } = await supabase
    .from("question_papers")
    .select(`
      *,
      syllabus:syllabus_id (
        id,
        course_name,
        course_code,
        semester
      )
    `)
    .eq("id", id)
    .single();

  if (paperError || !questionPaper) {
    console.error("Error fetching question paper:", paperError);
    return null;
  }

  // Fetch questions with their ideal answers
  const { data: questions, error: questionsError } = await supabase
    .from("questions")
    .select(`
      *,
      ideal_answers (*)
    `)
    .eq("question_paper_id", id)
    .order("question_number", { ascending: true });

  if (questionsError) {
    console.error("Error fetching questions:", questionsError);
    return { questionPaper, questions: [] };
  }

  return { questionPaper, questions: questions || [] };
}

export default async function QuestionPaperReviewPage({ params }: { params: { id: string } }) {
  const data = await getQuestionPaperData(params.id);

  if (!data) {
    notFound();
  }

  const { questionPaper, questions } = data;
  const syllabus = questionPaper.syllabus as any;

  return (
    <div className="container mx-auto py-8 px-4 max-w-7xl">
      {/* Breadcrumb */}
      <Breadcrumb className="mb-6">
        <BreadcrumbList>
          <BreadcrumbItem>
            <BreadcrumbLink href="/">Home</BreadcrumbLink>
          </BreadcrumbItem>
          <BreadcrumbSeparator />
          <BreadcrumbItem>
            <BreadcrumbLink href="/questions">Question Papers</BreadcrumbLink>
          </BreadcrumbItem>
          <BreadcrumbSeparator />
          <BreadcrumbItem>
            <BreadcrumbPage>Review & Edit</BreadcrumbPage>
          </BreadcrumbItem>
        </BreadcrumbList>
      </Breadcrumb>

      {/* Header */}
      <div className="mb-8">
        <h1 className="text-3xl font-bold mb-2">Review AI-Generated Answers</h1>
        <p className="text-muted-foreground">
          Review and edit the ideal answers generated by AI for evaluation purposes
        </p>
      </div>

      {/* Question Paper Info Card */}
      <Card className="mb-8">
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <FileText className="h-5 w-5" />
            {questionPaper.title}
          </CardTitle>
          <CardDescription>
            {syllabus?.course_name} ({syllabus?.course_code}) - {syllabus?.semester}
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="flex flex-wrap gap-6 text-sm">
            {questionPaper.exam_date && (
              <div className="flex items-center gap-2">
                <Calendar className="h-4 w-4 text-muted-foreground" />
                <span>
                  {new Date(questionPaper.exam_date).toLocaleDateString("en-US", {
                    year: "numeric",
                    month: "long",
                    day: "numeric",
                  })}
                </span>
              </div>
            )}
            {questionPaper.total_marks && (
              <div className="flex items-center gap-2">
                <Award className="h-4 w-4 text-muted-foreground" />
                <span>Total Marks: {questionPaper.total_marks}</span>
              </div>
            )}
            <div className="flex items-center gap-2">
              <FileText className="h-4 w-4 text-muted-foreground" />
              <span>{questions.length} Questions</span>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Questions Review */}
      <Suspense fallback={<ReviewSkeleton />}>
        <QuestionReviewClient
          questionPaperId={params.id}
          questions={questions}
        />
      </Suspense>
    </div>
  );
}

function ReviewSkeleton() {
  return (
    <div className="space-y-6">
      {[1, 2, 3].map((i) => (
        <Card key={i}>
          <CardHeader>
            <Skeleton className="h-6 w-3/4" />
            <Skeleton className="h-4 w-1/2 mt-2" />
          </CardHeader>
          <CardContent>
            <Skeleton className="h-32 w-full" />
          </CardContent>
        </Card>
      ))}
    </div>
  );
}
